import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import '../services/gemini_service.dart';

class PdfService {
  // ── Generate Student Report PDF ────────────────────────────────────────
  Future<void> generateStudentReport({
    required String studentName,
    required String examName,
    required String subject,
    required String date,
    required ExamEvaluationResult result,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => _buildHeader(examName, subject, date),
        footer: (context) => _buildFooter(context),
        build: (context) => [
          // Student info
          _buildStudentInfo(studentName, result),
          pw.SizedBox(height: 24),

          // Score summary
          _buildScoreSummary(result),
          pw.SizedBox(height: 24),

          // Overall feedback
          _buildOverallFeedback(result.overallFeedback),
          pw.SizedBox(height: 24),

          // Question-wise results
          _buildQuestionResults(result),
        ],
      ),
    );

    // Show print/share dialog
    await Printing.layoutPdf(
      onLayout: (format) async => pdf.save(),
      name: '${studentName}_${examName}_Report.pdf',
    );
  }

  // ── Header ─────────────────────────────────────────────────────────────
  pw.Widget _buildHeader(String examName, String subject, String date) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          bottom: pw.BorderSide(
            color: PdfColors.blue700,
            width: 2,
          ),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'EvalAI',
                style: pw.TextStyle(
                  fontSize: 24,
                  fontWeight: pw.FontWeight.bold,
                  color: PdfColors.blue700,
                ),
              ),
              pw.Text(
                'Smart Evaluation Report',
                style: pw.TextStyle(
                  fontSize: 12,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.end,
            children: [
              pw.Text(
                examName,
                style: pw.TextStyle(
                  fontSize: 14,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                '$subject • $date',
                style: pw.TextStyle(
                  fontSize: 11,
                  color: PdfColors.grey600,
                ),
              ),
            ],
          ),
        ],
      ),
    );
  }

  // ── Footer ─────────────────────────────────────────────────────────────
  pw.Widget _buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(
          top: pw.BorderSide(color: PdfColors.grey300),
        ),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text(
            'Generated by EvalAI',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey500,
            ),
          ),
          pw.Text(
            'Page ${context.pageNumber} of ${context.pagesCount}',
            style: pw.TextStyle(
              fontSize: 10,
              color: PdfColors.grey500,
            ),
          ),
        ],
      ),
    );
  }

  // ── Student Info ───────────────────────────────────────────────────────
  pw.Widget _buildStudentInfo(
      String studentName,
      ExamEvaluationResult result,
      ) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        color: PdfColors.blue50,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        children: [
          pw.Container(
            width: 50,
            height: 50,
            decoration: pw.BoxDecoration(
              color: PdfColors.blue700,
              borderRadius: pw.BorderRadius.circular(25),
            ),
            child: pw.Center(
              child: pw.Text(
                studentName[0].toUpperCase(),
                style: pw.TextStyle(
                  color: PdfColors.white,
                  fontSize: 22,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
            ),
          ),
          pw.SizedBox(width: 16),
          pw.Expanded(
            child: pw.Column(
              crossAxisAlignment: pw.CrossAxisAlignment.start,
              children: [
                pw.Text(
                  studentName,
                  style: pw.TextStyle(
                    fontSize: 18,
                    fontWeight: pw.FontWeight.bold,
                  ),
                ),
                pw.SizedBox(height: 4),
                pw.Text(
                  'Total Score: ${result.totalMarksAwarded}/${result.totalMarks} (${result.percentage.toStringAsFixed(1)}%)',
                  style: pw.TextStyle(
                    fontSize: 12,
                    color: PdfColors.grey700,
                  ),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  // ── Score Summary ──────────────────────────────────────────────────────
  pw.Widget _buildScoreSummary(ExamEvaluationResult result) {
    final percentage = result.percentage;
    PdfColor scoreColor;
    String grade;

    if (percentage >= 90) {
      scoreColor = PdfColors.green700;
      grade = 'A+';
    } else if (percentage >= 80) {
      scoreColor = PdfColors.green600;
      grade = 'A';
    } else if (percentage >= 70) {
      scoreColor = PdfColors.blue700;
      grade = 'B';
    } else if (percentage >= 60) {
      scoreColor = PdfColors.orange700;
      grade = 'C';
    } else if (percentage >= 50) {
      scoreColor = PdfColors.orange800;
      grade = 'D';
    } else {
      scoreColor = PdfColors.red700;
      grade = 'F';
    }

    return pw.Container(
      padding: const pw.EdgeInsets.all(20),
      decoration: pw.BoxDecoration(
        color: PdfColors.grey100,
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceAround,
        children: [
          _buildSummaryItem(
            'Marks',
            '${result.totalMarksAwarded}/${result.totalMarks}',
            PdfColors.blue700,
          ),
          _buildSummaryItem(
            'Percentage',
            '${percentage.toStringAsFixed(1)}%',
            scoreColor,
          ),
          _buildSummaryItem('Grade', grade, scoreColor),
          _buildSummaryItem(
            'Status',
            percentage >= 50 ? 'PASS' : 'FAIL',
            percentage >= 50 ? PdfColors.green700 : PdfColors.red700,
          ),
        ],
      ),
    );
  }

  pw.Widget _buildSummaryItem(String label, String value, PdfColor color) {
    return pw.Column(
      children: [
        pw.Text(
          value,
          style: pw.TextStyle(
            fontSize: 20,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
        pw.SizedBox(height: 4),
        pw.Text(
          label,
          style: pw.TextStyle(
            fontSize: 11,
            color: PdfColors.grey600,
          ),
        ),
      ],
    );
  }

  // ── Overall Feedback ───────────────────────────────────────────────────
  pw.Widget _buildOverallFeedback(String feedback) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(16),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.blue200),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(
            'AI Feedback',
            style: pw.TextStyle(
              fontSize: 14,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.blue700,
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            feedback,
            style: pw.TextStyle(
              fontSize: 12,
              lineSpacing: 4,
              color: PdfColors.grey800,
            ),
          ),
        ],
      ),
    );
  }

  // ── Question Results ───────────────────────────────────────────────────
  pw.Widget _buildQuestionResults(ExamEvaluationResult result) {
    return pw.Column(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          'Question-wise Analysis',
          style: pw.TextStyle(
            fontSize: 16,
            fontWeight: pw.FontWeight.bold,
          ),
        ),
        pw.SizedBox(height: 12),
        ...result.questionResults.map((q) => _buildQuestionCard(q)),
      ],
    );
  }

  pw.Widget _buildQuestionCard(EvaluationResult q) {
    final percentage = q.percentage;
    PdfColor color;

    if (percentage >= 75) {
      color = PdfColors.green700;
    } else if (percentage >= 50) {
      color = PdfColors.orange700;
    } else {
      color = PdfColors.red700;
    }

    return pw.Container(
      margin: const pw.EdgeInsets.only(bottom: 12),
      padding: const pw.EdgeInsets.all(14),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: pw.BorderRadius.circular(8),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          // Question header
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Text(
                'Question ${q.questionNumber}',
                style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                ),
              ),
              pw.Text(
                '${q.marksAwarded}/${q.totalMarks} marks',
                style: pw.TextStyle(
                  fontSize: 13,
                  fontWeight: pw.FontWeight.bold,
                  color: color,
                ),
              ),
            ],
          ),

          pw.SizedBox(height: 8),
          pw.Divider(color: PdfColors.grey300),
          pw.SizedBox(height: 8),

          // Strengths
          _buildFeedbackItem('✓ Strengths', q.strengths, PdfColors.green700),
          pw.SizedBox(height: 6),

          // Weaknesses
          _buildFeedbackItem('✗ Weaknesses', q.weaknesses, PdfColors.red700),
          pw.SizedBox(height: 6),

          // Suggestions
          _buildFeedbackItem(
              '→ Suggestion', q.suggestions, PdfColors.blue700),
        ],
      ),
    );
  }

  pw.Widget _buildFeedbackItem(String label, String text, PdfColor color) {
    return pw.Row(
      crossAxisAlignment: pw.CrossAxisAlignment.start,
      children: [
        pw.Text(
          '$label: ',
          style: pw.TextStyle(
            fontSize: 11,
            fontWeight: pw.FontWeight.bold,
            color: color,
          ),
        ),
        pw.Expanded(
          child: pw.Text(
            text,
            style: pw.TextStyle(
              fontSize: 11,
              color: PdfColors.grey800,
            ),
          ),
        ),
      ],
    );
  }
}