import 'dart:typed_data';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import '../models/user_model.dart';
import '../models/exam_model.dart';
import '../models/evaluation_model.dart';
import 'gemini_service.dart';

class PdfReportService {
  static Future<Uint8List> buildPdfForStudent(
    PdfPageFormat format, {
    required StudentModel student,
    required ExamModel exam,
    required ExamEvaluationResult result,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // ─── Header Section ───
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('OFFICIAL EVALUATION REPORT', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                    pw.SizedBox(height: 4),
                    pw.Text('Generated by EvalAI Automated Console', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                  ],
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  decoration: pw.BoxDecoration(
                    color: result.percentage >= 50 ? PdfColors.green100 : PdfColors.red100,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                  ),
                  child: pw.Text(
                    '${result.totalMarksAwarded} / ${result.totalMarks}',
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: result.percentage >= 50 ? PdfColors.green800 : PdfColors.red800,
                    ),
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 24),

            // ─── Student & Exam Details ───
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Student: ${student.name}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Roll No: ${student.rollNumber} | Class: ${student.className}'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Exam: ${exam.name}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Subject: ${exam.subject}'),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            // ─── AI Overall Feedback ───
            pw.Text('Instructor / AI Feedback', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Text(result.overallFeedback, style: const pw.TextStyle(fontSize: 11, lineSpacing: 1.5)),
            pw.SizedBox(height: 24),

            // ─── Question Breakdown Table ───
            pw.Text('Question Breakdown', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              context: context,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200))),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: const {
                0: pw.FlexColumnWidth(1.2),
                1: pw.FlexColumnWidth(1.8),
                2: pw.FlexColumnWidth(7.0),
              },
              data: <List<String>>[
                <String>['Q No', 'Score', 'Strengths / AI Remarks'],
                ...result.questionResults.map((q) => [
                  'Q${q.questionNumber}',
                  '${q.marksAwarded}/${q.totalMarks}',
                  q.strengths,
                ]),
              ],
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }

  static Future<Uint8List> buildPdfFromEvaluation(PdfPageFormat format, EvaluationModel evaluation, {String subject = ''}) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.MultiPage(
        pageFormat: format,
        margin: const pw.EdgeInsets.all(32),
        build: (pw.Context context) {
          return [
            // ─── Header Section ───
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Column(
                  crossAxisAlignment: pw.CrossAxisAlignment.start,
                  children: [
                    pw.Text('OFFICIAL EVALUATION REPORT', style: pw.TextStyle(fontSize: 20, fontWeight: pw.FontWeight.bold, color: PdfColors.blue800)),
                    pw.SizedBox(height: 4),
                    pw.Text('Generated by EvalAI Automated Console', style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
                  ],
                ),
                pw.Container(
                  padding: const pw.EdgeInsets.symmetric(horizontal: 12, vertical: 8),
                  decoration: pw.BoxDecoration(
                    color: evaluation.isPassed ? PdfColors.green100 : PdfColors.red100,
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
                  ),
                  child: pw.Text(
                    '${evaluation.totalMarksAwarded} / ${evaluation.totalMarks}',
                    style: pw.TextStyle(
                      fontSize: 18,
                      fontWeight: pw.FontWeight.bold,
                      color: evaluation.isPassed ? PdfColors.green800 : PdfColors.red800,
                    ),
                  ),
                ),
              ],
            ),
            pw.SizedBox(height: 24),

            // ─── Student & Exam Details ───
            pw.Container(
              padding: const pw.EdgeInsets.all(12),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(8)),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Student: ${evaluation.studentName}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      pw.Text('Roll No: ${evaluation.studentRollNumber}'),
                    ],
                  ),
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.end,
                    children: [
                      pw.Text('Exam: ${evaluation.examName}', style: pw.TextStyle(fontWeight: pw.FontWeight.bold)),
                      if (subject.isNotEmpty) pw.Text('Subject: $subject'),
                    ],
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 24),

            // ─── AI Overall Feedback ───
            pw.Text('Instructor / AI Feedback', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.Text(evaluation.overallFeedback, style: const pw.TextStyle(fontSize: 11, lineSpacing: 1.5)),
            pw.SizedBox(height: 24),

            // ─── Question Breakdown Table ───
            pw.Text('Question Breakdown', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
            pw.SizedBox(height: 8),
            pw.TableHelper.fromTextArray(
              context: context,
              headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, color: PdfColors.white),
              headerDecoration: const pw.BoxDecoration(color: PdfColors.blue800),
              rowDecoration: const pw.BoxDecoration(border: pw.Border(bottom: pw.BorderSide(color: PdfColors.grey200))),
              cellAlignment: pw.Alignment.centerLeft,
              columnWidths: const {
                0: pw.FlexColumnWidth(1.2),
                1: pw.FlexColumnWidth(1.8),
                2: pw.FlexColumnWidth(7.0),
              },
              data: <List<String>>[
                <String>['Q No', 'Score', 'Strengths / AI Remarks'],
                ...evaluation.questionResults.map((q) => [
                  'Q${q.questionNumber}',
                  '${q.marksAwarded}/${q.totalMarks}',
                  q.strengths,
                ]),
              ],
            ),
          ];
        },
      ),
    );

    return pdf.save();
  }
}